add logic game
Atikingi/Rock-Paper-Scissors pull request #1
Opened 2022-07-15 12:24 UTC by Atikingi

Сделана курсовая работа по теме Javascript в браузере https://skyengpublic.notion.site/JavaScript-f1a7bd0f17aa4e2f82ee6b93a1269c65

Создана мультиплеерная игра камень-ножницы-бумага на мощностях бэкенда от скайпро.
Поддерживается только игра с реальными игроками.

Использованы самописные библиотеки, которые делали в течении курса (template-engine и request) Для отправки запросов на бэк и генерации блоков.

Дизайн придуман с нуля. Также добавлена логика с sessionStorage, чтобы при обновлении страницы в большинстве случаев попадать на экран в зависимости от статуса игры.

2022-07-17 12:31 UTC, mrerberg requested changes

2022-07-17 12:31 UTC, mrerberg commented on rock-paper-scissors/index.html
> +<html lang="en">
Сайт на русском же?

2022-07-17 12:31 UTC, mrerberg commented on rock-paper-scissors/src/api.js
> +  playerStatus(token, onSuccess) {
checkPlayerStatus, с глагола предпочтительнее именовать функции

2022-07-17 12:31 UTC, mrerberg commented on rock-paper-scissors/src/api.js
> +        console.log('Server error');
Вынеси это в стандартный метод обработки ошибки, чтобы не копипастить)

2022-07-17 12:31 UTC, mrerberg commented on rock-paper-scissors/src/api.js
> +        console.log('Server error');
В метод класса

2022-07-17 12:31 UTC, mrerberg commented on rock-paper-scissors/src/api.js
> +  gameStatus(token, id, onSuccess) {
getGameStatus? checkGameStatus?

2022-07-17 12:31 UTC, mrerberg commented on rock-paper-scissors/src/api.js
> +// const gameAPI = new GameAPI();
Мертвый код

2022-07-17 12:31 UTC, mrerberg commented on rock-paper-scissors/src/game-event.js
> +  API = new GameAPI();
Поля классы обычно помещают над конструктором, потом конструктор, потом идут методы

2022-07-17 12:31 UTC, mrerberg commented on rock-paper-scissors/src/game-event.js
> +  GAME_ID = sessionStorage.getItem('id') ? sessionStorage.getItem('id') : '';
sessionStorage.getItem('id') || ''

2022-07-17 12:31 UTC, mrerberg commented on rock-paper-scissors/src/game-event.js
> +  GAME_ID = sessionStorage.getItem('id') ? sessionStorage.getItem('id') : '';
Ты можешь добавить абстракцию в виде класса, которая будет под капотом работать с sessionStorage, скрывая детали реализации от остальной системы, выдавая лишь токен из какого-то там источника.

2022-07-17 12:31 UTC, mrerberg commented on rock-paper-scissors/style/style.scss
> +    &1{
:nth-of-type не подойдет?

2022-07-17 12:31 UTC, mrerberg commented on rock-paper-scissors/style/style.scss
> +@font-face {
Подключение шрифтов можно вынести в отдельный _fonts модуль и сюда его импортнуть

2022-07-17 12:31 UTC, mrerberg commented on rock-paper-scissors/style/style.scss
> +    @keyframes login-error {
Анимацию можно вынести, не обязательно ее декларировать внутри класса (game)

2022-07-17 12:31 UTC, mrerberg commented on rock-paper-scissors/style/style.scss
> +  &__finish-title{
код частично не отформатирован. Почему после имени класса нет отступа? 

finish-title {

2022-07-17 12:31 UTC, mrerberg commented on rock-paper-scissors/style/style.scss
> +    transition: all 1.0s ease-in;
Вешать анимацию на all опасно. Попробуй где-нибудь сделать textarea, навесить на all анимацию и попробовать начать ей изменять размеры (через растягивания textarea за правый нижний угол). Будут просадки по перфомансу

2022-07-17 12:31 UTC, mrerberg commented on rock-paper-scissors/style/_media.scss
> +@media all and (max-width:376px){
Зачем тебе all?

2022-07-17 12:31 UTC, mrerberg commented on rock-paper-scissors/src/game-event.js
> +        if (response['game-status'].status === 'waiting-for-your-move') {
> 'waiting-for-your-move'

Значения статусов я бы вынес в переменные

2022-07-18 06:46 UTC, Atikingi commented on rock-paper-scissors/index.html
> +<html lang="en">
Нет, полностью английский

2022-07-18 06:59 UTC, Atikingi commented on rock-paper-scissors/src/api.js
> +  playerStatus(token, onSuccess) {
Исправил

2022-07-18 06:59 UTC, Atikingi commented on rock-paper-scissors/src/api.js
> +        console.log('Server error');
Исправил

2022-07-18 07:01 UTC, Atikingi commented on rock-paper-scissors/src/api.js
> +  gameStatus(token, id, onSuccess) {
исправил

2022-07-18 07:01 UTC, Atikingi commented on rock-paper-scissors/src/api.js
> +// const gameAPI = new GameAPI();
Удалил

2022-07-18 07:10 UTC, Atikingi commented on rock-paper-scissors/src/game-event.js
> +  API = new GameAPI();
Исправил

2022-07-18 07:47 UTC, Atikingi commented on rock-paper-scissors/src/game-event.js
> +  GAME_ID = sessionStorage.getItem('id') ? sessionStorage.getItem('id') : '';
Добавил класс

2022-07-18 07:47 UTC, Atikingi commented on rock-paper-scissors/src/game-event.js
> +  GAME_ID = sessionStorage.getItem('id') ? sessionStorage.getItem('id') : '';
Исправил

2022-07-18 07:53 UTC, Atikingi commented on rock-paper-scissors/src/game-event.js
> +        if (response['game-status'].status === 'waiting-for-your-move') {
Исправил

2022-07-18 08:05 UTC, Atikingi commented on rock-paper-scissors/style/style.scss
> +@font-face {
Исправил

2022-07-18 08:05 UTC, Atikingi commented on rock-paper-scissors/style/style.scss
> +    @keyframes login-error {
Вынес

2022-07-18 08:05 UTC, Atikingi commented on rock-paper-scissors/style/style.scss
> +  &__finish-title{
исправил

2022-07-18 08:11 UTC, Atikingi commented on rock-paper-scissors/style/_media.scss
> +@media all and (max-width:376px){
Исправил

2022-07-18 08:28 UTC, Atikingi commented on rock-paper-scissors/style/style.scss
> +    &1{
Подошел)

2022-07-18 08:29 UTC, Atikingi commented on rock-paper-scissors/style/style.scss
> +    transition: all 1.0s ease-in;
Исправил

2022-07-19 07:09 UTC, mrerberg requested changes

2022-07-19 07:09 UTC, mrerberg commented on rock-paper-scissors/src/game-event.js
> +        const statuses = {
Это можно вынести в константы игры, а не только метода, и ключи именовать в удобном для использовании формате

waitingPlayer
...

Чтобы избежать [] для обращения по ключу

2022-07-19 07:41 UTC, Atikingi commented on rock-paper-scissors/src/game-event.js
> +        const statuses = {
Вынес

2022-07-20 08:40 UTC, merged